### ISSUE TITLE
Process files in parallel

### ISSUE THREAD

**Issue by sahilsuneja1** [zipnn/zipnn#14]
The compression/decompression scripts currently process one file at a time.
Can they can be enhanced to do all files in parallel in a directory, assuming there is nothing in the zipnn code that prevents multiple parallel invocations?

**Comment by moshik1** [comment]
Thanks for pointing it out and opening an issue.
You are right. The processing can be done in parallel. 
Let's first have the multi-threading and see if this is needed.

**Comment by moshik1** [comment]
Solved in version 0.3.1
